# Generated by Django 5.2.9 on 2025-12-27 21:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_indexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='intro',
            field=wagtail.fields.StreamField([('title', 0), ('corpo', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
