# Generated by Django 5.2.9 on 2026-01-05 11:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('two_columns', 6), ('rich_text', 7), ('raw_html', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo (esquerda)', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto (esquerda)', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem/ícone frontal (esquerda)', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo (direita)', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto (direita)', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem/ícone frontal (direita)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('background_image_left', 0), ('text_left', 1), ('front_image_left', 2), ('background_image_right', 3), ('text_right', 4), ('front_image_right', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto livre'}), 8: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML/Embed'})}),
        ),
    ]
