# Generated by Django 5.2.9 on 2026-01-05 20:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('two_columns', 7), ('full_width', 10), ('rich_text', 11), ('raw_html', 12)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo (esquerda)', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML/Embed'}), 4: ('wagtail.blocks.StreamBlock', [[('rich_text', 1), ('image', 2), ('raw_html', 3)]], {'label': 'Conteúdo (esquerda)', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo (direita)', 'required': False}), 6: ('wagtail.blocks.StreamBlock', [[('rich_text', 1), ('image', 2), ('raw_html', 3)]], {'label': 'Conteúdo (direita)', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('background_image_left', 0), ('content_left', 4), ('background_image_right', 5), ('content_right', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo', 'required': False}), 9: ('wagtail.blocks.StreamBlock', [[('rich_text', 1), ('image', 2), ('raw_html', 3)]], {'label': 'Conteúdo', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('background_image', 8), ('content', 9)]], {}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto livre'}), 12: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML/Embed grande'})}),
        ),
    ]
