# Generated by Django 5.2.9 on 2026-01-06 16:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('two_columns', 8), ('full_width', 11), ('rich_text', 12), ('raw_html', 13)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'default': 300, 'help_text': 'Defina a altura dos blocos', 'label': 'Altura mínima (px)', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo (esquerda)', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML/Embed'}), 5: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('image', 3), ('raw_html', 4)]], {'label': 'Conteúdo (esquerda)', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo (direita)', 'required': False}), 7: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('image', 3), ('raw_html', 4)]], {'label': 'Conteúdo (direita)', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('min_height', 0), ('background_image_left', 1), ('content_left', 5), ('background_image_right', 6), ('content_right', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de fundo', 'required': False}), 10: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('image', 3), ('raw_html', 4)]], {'label': 'Conteúdo', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('min_height', 0), ('background_image', 9), ('content', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto livre'}), 13: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML/Embed grande'})}),
        ),
    ]
