# Generated by Django 5.2.9 on 2025-12-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Linkedin')),
                ('zap_url', models.URLField(blank=True, help_text='(wa.me/+55seunumeroaqui)', verbose_name="What's App")),
                ('github_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('banner_url1', models.URLField(blank=True, help_text='URL opcional da imagem 1)', verbose_name='Link Imagem 1')),
                ('banner_url2', models.URLField(blank=True, help_text='URL opcional da imagem 2)', verbose_name='Link Imagem 2')),
                ('banner_image1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner 1 (800x110px)')),
                ('banner_image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner 2 (opcional)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
