# Generated by Django 5.2.9 on 2025-12-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='face_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
    ]
