# Generated by Django 5.2.9 on 2025-12-29 12:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_footersettings_face_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texto do Rodapé'),
        ),
    ]
