# Generated by Django 5.2.9 on 2026-01-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footersettings_footer_text'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='banner_image2',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='banner_url2',
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url1', models.URLField(blank=True, help_text='URL opcional da imagem 1)', verbose_name='Link Imagem 1')),
                ('banner_url2', models.URLField(blank=True, help_text='URL opcional da imagem 2)', verbose_name='Link Imagem 2')),
                ('banner_url3', models.URLField(blank=True, help_text='URL opcional da imagem 3)', verbose_name='Link Imagem 3')),
                ('banner_image1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner 1 (800x110px)')),
                ('banner_image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner 2 (800x110px)')),
                ('banner_image3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner 3 (800x110px)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
